### PR TITLE
fix: disable custom querier

### PR DESCRIPTION
**Pull request by loloicci**
## Description

This PR closes the custom querier for other modules.

closes: #115

## Motivation and context

Since https://github.com/Finschia/finschia-sdk/commit/0f4ad5b90256b8b1cca6c81286124a10bde26a5c, custom query is opened for our token/collection module.
It is not as expected this is still alive after we separate x/wasm and x/wasmplus.
So this PR deletes it.

Alternative queries for our original modules are going to be opened with the stargate query feature in later versions.

## How has this been tested?

After merging, the default custom querier is the same as upstream.

## Checklist:

- [x] I followed the [contributing guidelines](https://github.com/Finschia/wasmd/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/Finschia/wasmd/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes. (not needed)
- [ ] I have updated the documentation accordingly. (not needed)
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml` (not needed)

### CODE REVIEW

**Review by zemyblue — COMMENTED** [review]
Please add changelog.

**Comment by loloicci** [comment]
> Please add changelog.

Sorry, I missed to stage the change. Thanks for your find!

**Comment by 170210** [comment]
Please modify the description in https://github.com/Finschia/wasmd/blob/main/INTEGRATION.md#calling-into-the-sdk

**Review by 170210 — APPROVED** [review]
LGTM

**Pull request merged**
