### PR TITLE
test: add the test case for invalid address

### PR DESCRIPTION
**Pull request by kokeshiM0chi**
## Description
Added an error test when specifying an invalid address

## Checklist:

- [x] I followed the [contributing guidelines](https://github.com/Finschia/wasmd/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/Finschia/wasmd/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added a relevant changelog to `CHANGELOG.md`
- [x] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly. (not needed)
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml` (not needed)

### CODE REVIEW

**Review by da1suk8 — APPROVED** [review]

**Review by 170210 — COMMENTED** [review]
I think it's necessary to have the same test cases in "TestQueryContractInfo" and "TestQueryContractHistory" as well.

**Comment by loloicci** [comment]
How about using https://pkg.go.dev/github.com/stretchr/testify/assert#ErrorContains to compare errors and not import bech32 error type?

**Comment by kokeshiM0chi** [comment]
@loloicci 
Thank you for your advice.  I considered it. This test can be done without importing bech32 in this file if ErrorContaions is used, but equal test is more reliable. Error checking is fine as is. Also, since it was already imported with go.mod, there was no need to stick to not importing. So I will leave it as is.
https://github.com/Finschia/wasmd/blob/main/go.mod#L54

**Review by dudong2 — DISMISSED** [review]

**Review by loloicci — DISMISSED** [review]

**Review by da1suk8 — DISMISSED** [review]

**Review by da1suk8 — APPROVED** [review]

**Review by 170210 — APPROVED** [review]

**Comment by kokeshiM0chi** [comment]
Commits other than the ones below are unsquashed merge commits from other PRs.
https://github.com/Finschia/wasmd/pull/88/commits/6e2e797e73793e72c5816ea1046fac509439df2c
https://github.com/Finschia/wasmd/pull/88/commits/8b6ceb9d13d1e81a7b6bcbfa71025c4f4a78e74e
https://github.com/Finschia/wasmd/pull/88/commits/0b3c700ac035442eb59b74a4f5d304f478334d44

**Pull request merged**
