### PR TITLE
fix: delete unnecessary test

### PR DESCRIPTION
**Pull request by da1suk8**
## Description

closes: #39 

This test was moved from finschia-sdk by https://github.com/Finschia/wasmd/pull/1 and added by https://github.com/Finschia/finschia-sdk/pull/470.

Previously, a function called `UpdateContractStatus()` was used in https://github.com/Finschia/finschia-sdk/pull/470/commits/bde56b916605921468938c26ebd3155da12c4d54, 
but it was removed from wasmd and has become a meaningless test.

Further checking with https://github.com/Finschia/wasmd/issues/48, active/inactive management is done by wasmplus.
https://github.com/Finschia/wasmd/blob/ff18c5493565b88eb8cb1ecb5312218168110173/x/wasmplus/keeper/contract_keeper.go#L15-L16

In the test I deleted, "contract status", which was checked by `UpdateContractStatus()`, is not used in the current wasmd, so there is no problem in deleting it.

And when you use `UpdateContractStatus()` before, you could only change it via gov proposal, which was tested, but is no longer necessary.

So I think it is better to remove this test.

## Motivation and context

I don't want to leave a meaningless test.

## Checklist:

- [x] I followed the [contributing guidelines](https://github.com/Finschia/wasmd/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/Finschia/wasmd/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes.
- [x] I have updated the documentation accordingly.
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

### CODE REVIEW

**Review by loloicci — COMMENTED** [review]
Is there a test doing as same as the test at https://github.com/Finschia/finschia-sdk/commit/bde56b916605921468938c26ebd3155da12c4d54 in x/wasmplus?

**Comment by da1suk8** [comment]
I'll check.

**Comment by da1suk8** [comment]
@loloicci 

This test do almost the same thing.

https://github.com/Finschia/wasmd/blob/74de5b2455198380190d0a65181ada8da15edbe1/x/wasmplus/keeper/keeper_test.go#L37-L55

**Comment by kokeshiM0chi** [comment]
Is my understanding below correct?

The intent of the test is to execute an `inactive contract` and return an error, but the function `UpdateContractStatus()`
which was used in that case, has been eliminated. In addition, the test to confirm the execution of an `inactive contract` and the return of an error is performed by `TestDeactivateContract`. Therefore, the `TestExecuteManualInactiveContractFailure()` should be removed.

**Review by kokeshiM0chi — COMMENTED** [review]
Is my understanding below correct?

The intent of the test is to execute an inactive contract and return an error, but the function UpdateContractStatus()
which was used in that case, has been eliminated. In addition, the test to confirm the execution of an inactive contract and the return of an error is performed by TestDeactivateContract. Therefore, the TestExecuteManualInactiveContractFailure() should be removed.

**Comment by da1suk8** [comment]
@kokeshiM0chi 
Yes, your understanding is correct.

**Review by kokeshiM0chi — APPROVED** [review]

**Comment by loloicci** [comment]
> This test do almost the same thing.

It looks not the same test. As bellow, the test you delete checks other ways than gov proposal cannot change the contract state.  https://github.com/Finschia/finschia-sdk/commit/bde56b916605921468938c26ebd3155da12c4d54#diff-591082558a25fcf8aa75120ea3d175720c0293fbde4bdf526ee60b491466a570L823-L827

**Comment by da1suk8** [comment]
@loloicci 

I understand that `UpdateContractStatus()`, which was used in this function, is deleted in https://github.com/Finschia/finschia-sdk/pull/625, and the handling of white list and black list is controlled by wasm (https://github.com/Finschia/finschia-sdk/pull/655).
My understanding is not correct?

So I am thinking that the role of the test I raised is the same.

**Comment by loloicci** [comment]
@da1suk8

> My understanding is not correct?

Well, I don't know. Because I cannot know whether

> is deleted in https://github.com/Finschia/finschia-sdk/pull/625, and the handling of white list and black list is controlled by wasm (https://github.com/Finschia/finschia-sdk/pull/655).

means the authorization to active/inactive contracts is not within the scope of x/wasmplus or not.

In any case, there are some tests checking authorization to active/inactive contracts works.

**Comment by da1suk8** [comment]
@loloicci 

After checking with another [PR](https://github.com/Finschia/wasmd/issues/48), I will respond to this PR.

**Review by zemyblue — COMMENTED** [review]
Please, update changelog.

**Comment by da1suk8** [comment]
@zemyblue 

Update CHANGELOG after this #48.
Thank you.

**Comment by zemyblue** [comment]
> @zemyblue
> 
> Update CHANGELOG after this #48. Thank you.

No, please update changelog with each PR.

**Comment by da1suk8** [comment]
@zemyblue 

Added.

**Comment by da1suk8** [comment]
As confirmed by this issue, active/inactive management is done by wasmplus.

https://github.com/Finschia/wasmd/blob/ff18c5493565b88eb8cb1ecb5312218168110173/x/wasmplus/keeper/contract_keeper.go#L15-L16

In the test I deleted, "contract status", which was checked by `UpdateContractStatus()`, is not used in the current wasmd, so there is no problem in deleting it.

**Review by zemyblue — APPROVED** [review]

**Review by loloicci — APPROVED** [review]

**Pull request merged**
